import './globals.css'
import Navbar from '@/components/navbar';
import ThemeProviders from '@/components/ThemeProviders';

export const metadata = {
  title: 'TrackStocks',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className='font-poppins bg-gray-300 dark:bg-[#151E3D]'>
        <ThemeProviders >
          <Navbar />
          {children}
        </ThemeProviders>
      </body>
    </html>
  )
}
