import './globals.css'
import Providers from '@/redux/provider';
import Navbar from '@/components/navbar';
import ThemeProviders from '@/components/ThemeProviders';

export const metadata = {
  title: 'TrackStocks',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className='font-poppins bg-gray-300 dark:bg-[#151E3D]'>
        <Providers >
          <ThemeProviders >
            <Navbar />
            {children}
          </ThemeProviders>
        </Providers>
      </body>
    </html>
  )
}
